---
- name: Configure Xubuntu Desktop for Trainee
  hosts: xubuntu-desktop
  gather_facts: yes
  become: yes

  vars:
    # Target username
    target_user: trainee

  roles:
    - name: user-access
      user_access_username: "{{ target_user }}"
      user_access_password: btcmp03
      user_access_sudo: true

  tasks:
    # 1. AccountsService configuration
    - name: Hide system account in login screen
      ansible.builtin.copy:
        content: |
          [User]
          SystemAccount=true
        dest: "/var/lib/AccountsService/users/ubuntu"
        mode: '0644'
- name: Set up command logging
  hosts: xubuntu-desktop
  become: yes
  roles:
    - role: sandbox-logging
      slf_destination_port: '{% if hostvars["man"] is defined -%} 514 {%- else -%} 515 {%- endif %}'

- name: Disable unattended apt upgrades
  hosts: man, xubuntu-desktop
  become: true
  tasks:
    - name: Disable unattended upgrades in apt periodic config
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        mode: "0644"
        content: |
          APT::Periodic::Update-Package-Lists "0";
          APT::Periodic::Unattended-Upgrade "0";
 
    - name: Disable apt daily timers
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
        masked: true
      loop:
        - apt-daily.timer
        - apt-daily-upgrade.timer
